// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"Webook/pkg/wego"
	"Webook/sms/grpc"
	"Webook/sms/ioc"
	"Webook/sms/repository"
	"Webook/sms/repository/dao"
	"Webook/sms/service/async"
)

// Injectors from wire.go:

func Init() *wego.App {
	service := ioc.InitSmsTencentService()
	logger := ioc.InitLogger()
	asyncService := async.NewAsyncService(service, logger, repository.NewAsyncSMSRepository(dao.NewGORMAsyncSmsDAO(ioc.InitDB(logger))))
	client := ioc.InitEtcdClient()
	smsServiceServer := grpc2.NewSmsServiceServer(asyncService)
	server := ioc.InitGRPCxServer(smsServiceServer, logger, client)
	app := &wego.App{
		GRPCServer: server,
	}
	return app
}
