// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"Webook/article/events"
	"Webook/article/grpc"
	"Webook/article/ioc"
	"Webook/article/repository"
	"Webook/article/repository/cache"
	"Webook/article/repository/dao"
	"Webook/article/service"
	"Webook/pkg/wego"
	"github.com/google/wire"
)

// Injectors from wire.go:

func Init() *wego.App {
	logger := ioc.InitLogger()
	db := ioc.InitDB()
	articleDAO := dao.NewGORMArticleDAO(db)
	cmdable := ioc.InitRedis()
	articleCache := cache.NewRedisArticleCache(cmdable)
	articleRepository := repository.NewArticleRepository(articleDAO, articleCache, db, logger)
	articleAuthorRepository := repository.NewArticleAuthorRepository(articleDAO)
	articleReaderDAO := dao.NewGORMArticleReaderDAO(db)
	articleReaderRepository := repository.NewCachedArticleReaderRepository(articleReaderDAO)
	usersServiceClient := ioc.InitUserRpcClient()
	authorRepository := repository.NewGrpcAuthorRepository(articleDAO, usersServiceClient)
	syncProducer := ioc.InitProducer()
	producer := events.NewSaramaSyncProducer(syncProducer)
	articleService := service.NewArticleService(logger, articleRepository, articleAuthorRepository, articleReaderRepository, authorRepository, producer)
	articleServiceServer := grpc2.NewArticleServiceServer(articleService)
	client := ioc.InitEtcdClient()
	server := ioc.InitGRPCxServer(articleServiceServer, logger, client)
	app := &wego.App{
		GRPCServer: server,
	}
	return app
}

// wire.go:

var thirdProvider = wire.NewSet(ioc.InitRedis, ioc.InitLogger, ioc.InitUserRpcClient, ioc.InitProducer, ioc.InitEtcdClient, ioc.InitDB)
