// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	artdao "Webook/article/repository/dao"
	"Webook/interactive/events"
	"Webook/interactive/grpc"
	"Webook/interactive/ioc"
	"Webook/interactive/repository"
	"Webook/interactive/repository/cache"
	"Webook/interactive/repository/dao"
	"Webook/interactive/service"
	"github.com/google/wire"
	xcontext "golang.org/x/net/context"
)

// Injectors from wire.go:

func Init() *App {
	logger := ioc.InitLogger()
	client := ioc.InitEtcdClient()
	cmdable := ioc.InitRedisClient()
	interactiveCache := cache.NewRedisInteractiveCache(cmdable)
	srcDB := ioc.InitSRC()
	dstDB := ioc.InitDST()
	doubleWritePool := ioc.InitDoubleWritePool(srcDB, dstDB)
	db := ioc.InitBizDB(doubleWritePool)
	interactiveDAO := dao.NewGORMInteractiveDAO(db)
	notificationDAO := dao.NewGORMNotificationDAO(db)
	interactiveRepository := repository.NewCachedInteractiveRepository(interactiveCache, interactiveDAO, logger)
	notificationRepository := repository.NewNotificationRepository(notificationDAO)
	saramaClient := ioc.InitKafka()
	syncProducer := ioc.InitProducer(saramaClient)
	interactiveEventsProducer := events.NewInteractiveProducer(syncProducer)
	interactiveService := service.NewInteractiveService(interactiveRepository, logger, interactiveEventsProducer)
	notificationService := service.NewNotificationService(notificationRepository)
	interactiveServiceServer := grpc2.NewInteractiveServiceServer(interactiveService, notificationService)
	server := ioc.InitGRPCxServer(logger, client, interactiveServiceServer)
	producer := ioc.InitMigratorProducer(syncProducer)
	ginxServer := ioc.InitMigratorWeb(logger, srcDB, dstDB, doubleWritePool, producer)
	interactiveReadEventConsumer := events.NewInteractiveReadEventConsumer(saramaClient, logger, interactiveRepository)
	articleDB := ioc.InitArticleDB()
	articleDAO := artdao.NewGORMArticleDAO(articleDB)
	resolveOwner := func(ctx xcontext.Context, biz string, bizId int64) (int64, error) {
		if biz == "article" {
			pa, err := articleDAO.GetPubById(ctx, bizId)
			if err != nil {
				return 0, err
			}
			return pa.AuthorId, nil
		}
		return 0, nil
	}
	likeEventConsumer := events.NewLikeEventConsumer(saramaClient, logger, interactiveRepository, resolveOwner)
	collectEventConsumer := events.NewCollectEventConsumer(saramaClient, logger, interactiveRepository, resolveOwner)
	notificationEventConsumer := events.NewNotificationEventConsumer(saramaClient, logger, notificationDAO, resolveOwner)
	consumer := ioc.InitFixDataConsumer(logger, srcDB, dstDB, saramaClient)
	v := ioc.NewConsumers(interactiveReadEventConsumer, likeEventConsumer, collectEventConsumer, notificationEventConsumer, consumer)
	app := &App{
		server:         server,
		migratorServer: ginxServer,
		consumers:      v,
	}
	return app
}

// wire.go:

var serviceProviderSet = wire.NewSet(dao.NewGORMInteractiveDAO, cache.NewRedisInteractiveCache, repository.NewCachedInteractiveRepository, service.NewInteractiveService)

var thirdProvider = wire.NewSet(ioc.InitSRC, ioc.InitDST, ioc.InitDoubleWritePool, ioc.InitBizDB, ioc.InitRedisClient, ioc.InitLogger, ioc.InitKafka, ioc.InitEtcdClient, ioc.InitProducer)

var migratorSet = wire.NewSet(ioc.InitMigratorWeb, ioc.InitFixDataConsumer, ioc.InitMigratorProducer)
