// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"Webook/interactive/events"
	"Webook/interactive/grpc"
	"Webook/interactive/ioc"
	"Webook/interactive/repository"
	"Webook/interactive/repository/cache"
	"Webook/interactive/repository/dao"
	"Webook/interactive/service"
	"github.com/google/wire"
)

// Injectors from wire.go:

func Init() *App {
	logger := ioc.InitLogger()
	client := ioc.InitEtcdClient()
	cmdable := ioc.InitRedisClient()
	interactiveCache := cache.NewRedisInteractiveCache(cmdable)
	srcDB := ioc.InitSRC()
	dstDB := ioc.InitDST()
	doubleWritePool := ioc.InitDoubleWritePool(srcDB, dstDB)
	db := ioc.InitBizDB(doubleWritePool)
	interactiveDAO := dao.NewGORMInteractiveDAO(db)
	interactiveRepository := repository.NewCachedInteractiveRepository(interactiveCache, interactiveDAO, logger)
	interactiveService := service.NewInteractiveService(interactiveRepository, logger)
	interactiveServiceServer := grpc2.NewInteractiveServiceServer(interactiveService)
	server := ioc.InitGRPCxServer(logger, client, interactiveServiceServer)
	saramaClient := ioc.InitKafka()
	syncProducer := ioc.InitProducer(saramaClient)
	producer := ioc.InitMigratorProducer(syncProducer)
	ginxServer := ioc.InitMigratorWeb(logger, srcDB, dstDB, doubleWritePool, producer)
	interactiveReadEventConsumer := events.NewInteractiveReadEventConsumer(saramaClient, logger, interactiveRepository)
	consumer := ioc.InitFixDataConsumer(logger, srcDB, dstDB, saramaClient)
	v := ioc.NewConsumers(interactiveReadEventConsumer, consumer)
	app := &App{
		server:         server,
		migratorServer: ginxServer,
		consumers:      v,
	}
	return app
}

// wire.go:

var serviceProviderSet = wire.NewSet(dao.NewGORMInteractiveDAO, cache.NewRedisInteractiveCache, repository.NewCachedInteractiveRepository, service.NewInteractiveService)

var thirdProvider = wire.NewSet(ioc.InitSRC, ioc.InitDST, ioc.InitDoubleWritePool, ioc.InitBizDB, ioc.InitRedisClient, ioc.InitLogger, ioc.InitKafka, ioc.InitEtcdClient, ioc.InitProducer)

var migratorSet = wire.NewSet(ioc.InitMigratorWeb, ioc.InitFixDataConsumer, ioc.InitMigratorProducer)
