// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"Webook/comment/events"
	"Webook/comment/grpc"
	"Webook/comment/ioc"
	"Webook/comment/repository"
	"Webook/comment/repository/dao"
	"Webook/comment/service"
	"github.com/google/wire"
)

// Injectors from wire.go:

func Init() *App {
	logger := ioc.InitLogger()
	client := ioc.InitEtcdClient()
	db := ioc.InitDB(logger)
	commentDAO := dao.NewGORMCommentDAO(db)
	commentRepository := repository.NewCommentRepo(commentDAO, logger)
	kafkaClient := ioc.InitKafka()
	syncProducer := ioc.InitProducer(kafkaClient)
	commentProducer := events.NewProducer(syncProducer)
	commentService := service.NewCommentSvc(commentRepository, commentProducer)
	commentServiceServer := grpc2.NewGrpcServer(commentService)
	server := ioc.InitGRPCxServer(logger, client, commentServiceServer)
	commentConsumer := events.NewCommentEventConsumer(kafkaClient, logger, commentRepository)
	consumers := ioc.NewConsumers(commentConsumer)
	app := &App{
		server:    server,
		consumers: consumers,
	}
	return app
}

// wire.go:

var serviceProviderSet = wire.NewSet(dao.NewGORMCommentDAO, repository.NewCommentRepo, service.NewCommentSvc, grpc2.NewGrpcServer)

var thirdProvider = wire.NewSet(ioc.InitLogger, ioc.InitDB, ioc.InitEtcdClient)
