// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"Webook/search/events"
	"Webook/search/grpc"
	"Webook/search/ioc"
	"Webook/search/repository"
	"Webook/search/repository/dao"
	"Webook/search/service"
	"github.com/google/wire"
)

// Injectors from wire.go:

func Init() *App {
	client := ioc.InitESClient()
	anyDAO := dao.NewAnyESDAO(client)
	anyRepository := repository.NewAnyRepository(anyDAO)
	userDAO := dao.NewUserElasticDAO(client)
	userRepository := repository.NewUserRepository(userDAO)
	articleDAO := dao.NewArticleElasticDAO(client)
	tagDAO := dao.NewTagESDAO(client)
	articleRepository := repository.NewArticleRepository(articleDAO, tagDAO)
	syncService := service.NewSyncService(anyRepository, userRepository, articleRepository)
	syncServiceServer := grpc2.NewSyncServiceServer(syncService)
	searchService := service.NewSearchService(userRepository, articleRepository)
	searchServiceServer := grpc2.NewSearchServiceServer(searchService)
	clientv3Client := ioc.InitEtcdClient()
	logger := ioc.InitLogger()
	server := ioc.InitGRPCxServer(syncServiceServer, searchServiceServer, clientv3Client, logger)
	saramaClient := ioc.InitKafka()
	articleConsumer := events.NewArticleConsumer(saramaClient, logger, syncService)
	userConsumer := events.NewUserConsumer(saramaClient, logger, syncService)
	v := ioc.NewConsumers(articleConsumer, userConsumer)
	app := &App{
		server:    server,
		consumers: v,
	}
	return app
}

// wire.go:

var serviceProviderSet = wire.NewSet(dao.NewUserElasticDAO, dao.NewArticleElasticDAO, dao.NewAnyESDAO, dao.NewTagESDAO, repository.NewUserRepository, repository.NewArticleRepository, repository.NewAnyRepository, service.NewSyncService, service.NewSearchService)

var thirdProvider = wire.NewSet(ioc.InitESClient, ioc.InitEtcdClient, ioc.InitLogger, ioc.InitKafka)
