// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"Webook/bff/ioc"
	"Webook/bff/web"
	"Webook/bff/web/jwt"
	"Webook/pkg/wego"
)

// Injectors from wire.go:

func InitApp() *wego.App {
	logger := ioc.InitLogger()
	cmdable := ioc.InitRedis()
	handler := jwt.NewRedisHandler(cmdable)
	client := ioc.InitEtcdClient()
	usersServiceClient := ioc.InitUserClient(client)
	codeServiceClient := ioc.InitCodeClient(client)
	userHandler := web.NewUserHandler(usersServiceClient, codeServiceClient, handler)
	articleServiceClient := ioc.InitArticleClient(client)
	interactiveServiceClient := ioc.InitIntrClient(client)
	rankingServiceClient := ioc.InitRankingClient(client)
	rewardServiceClient := ioc.InitRewardClient(client)
	commentServiceClient := ioc.InitCommentClient(client)
	articleHandler := ioc.NewArticleHandler(articleServiceClient, interactiveServiceClient, rankingServiceClient, rewardServiceClient, logger)
	rewardHandler := web.NewRewardHandler(rewardServiceClient, articleServiceClient)
	commentHandler := web.NewCommentHandler(commentServiceClient, usersServiceClient, logger)
	server := ioc.InitGinServer(logger, handler, userHandler, articleHandler, rewardHandler, commentHandler)
	app := &wego.App{
		WebServer: server,
	}
	return app
}
