// Code generated by MockGen. DO NOT EDIT.
// Source: ./author.go

// Package repomocks is a generated GoMock package.
package repomocks

import (
	domain "Webook/article/domain"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockAuthorRepository is a mock of AuthorRepository interface.
type MockAuthorRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAuthorRepositoryMockRecorder
}

// MockAuthorRepositoryMockRecorder is the mock recorder for MockAuthorRepository.
type MockAuthorRepositoryMockRecorder struct {
	mock *MockAuthorRepository
}

// NewMockAuthorRepository creates a new mock instance.
func NewMockAuthorRepository(ctrl *gomock.Controller) *MockAuthorRepository {
	mock := &MockAuthorRepository{ctrl: ctrl}
	mock.recorder = &MockAuthorRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthorRepository) EXPECT() *MockAuthorRepositoryMockRecorder {
	return m.recorder
}

// FindAuthor mocks base method.
func (m *MockAuthorRepository) FindAuthor(ctx context.Context, id int64) (domain.Author, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAuthor", ctx, id)
	ret0, _ := ret[0].(domain.Author)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAuthor indicates an expected call of FindAuthor.
func (mr *MockAuthorRepositoryMockRecorder) FindAuthor(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAuthor", reflect.TypeOf((*MockAuthorRepository)(nil).FindAuthor), ctx, id)
}
