// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"Webook/cronjob/grpc"
	"Webook/cronjob/ioc"
	"Webook/cronjob/repository"
	"Webook/cronjob/repository/dao"
	"Webook/cronjob/service"
	"Webook/pkg/grpcx"
	"github.com/google/wire"
)

// Injectors from wire.go:

func Init() *App {
	logger := ioc.InitLogger()
	db := ioc.InitDB(logger)
	jobDAO := dao.NewGORMJobDAO(db)
	cronJobRepository := repository.NewPreemptCronJobRepository(jobDAO)
	cronJobService := service.NewCronJobService(cronJobRepository, logger)
	cronJobServiceServer := grpc2.NewCronJobServiceServer(cronJobService)
	server := ioc.InitGRPCxServer(cronJobServiceServer)
	app := &App{
		server: server,
	}
	return app
}

// wire.go:

var serviceProviderSet = wire.NewSet(dao.NewGORMJobDAO, repository.NewPreemptCronJobRepository, service.NewCronJobService)

var thirdProvider = wire.NewSet(ioc.InitDB, ioc.InitLogger)

type App struct {
	server *grpcx.Server
}
