// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package startup

import (
	"Webook/interactive/grpc"
	"Webook/interactive/repository"
	"Webook/interactive/repository/cache"
	"Webook/interactive/repository/dao"
	"Webook/interactive/service"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitGRPCServer() *grpc2.InteractiveServiceServer {
	cmdable := InitRedis()
	interactiveCache := cache.NewRedisInteractiveCache(cmdable)
	gormDB := InitTestDB()
	interactiveDAO := dao.NewGORMInteractiveDAO(gormDB)
	notificationDAO := dao.NewGORMNotificationDAO(gormDB)
	logger := InitLog()
	interactiveRepository := repository.NewCachedInteractiveRepository(interactiveCache, interactiveDAO, logger)
	notificationRepository := repository.NewNotificationRepository(notificationDAO)
	interactiveService := service.NewInteractiveService(interactiveRepository, logger, nil)
	notificationService := service.NewNotificationService(notificationRepository)
	interactiveServiceServer := grpc2.NewInteractiveServiceServer(interactiveService, notificationService)
	return interactiveServiceServer
}

// wire.go:

var thirdProvider = wire.NewSet(
	InitRedis, InitTestDB,
	InitLog,
	InitKafka,
)
