// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package startup

import (
	"Webook/comment/grpc"
	"Webook/comment/repository"
	"Webook/comment/repository/dao"
	"Webook/comment/service"
	"Webook/pkg/logger"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitGRPCServer() *grpc2.CommentServiceServer {
	gormDB := InitTestDB()
	commentDAO := dao.NewGORMCommentDAO(gormDB)
	loggerLogger := logger.NewNoOpLogger()
	commentRepository := repository.NewCommentRepo(commentDAO, loggerLogger)
	commentService := service.NewCommentSvc(commentRepository)
	commentServiceServer := grpc2.NewGrpcServer(commentService)
	return commentServiceServer
}

// wire.go:

var serviceProviderSet = wire.NewSet(dao.NewGORMCommentDAO, repository.NewCommentRepo, service.NewCommentSvc, grpc2.NewGrpcServer)

var thirdProvider = wire.NewSet(logger.NewNoOpLogger, InitTestDB)
