// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"Webook/follow/events"
	"Webook/follow/grpc"
	"Webook/follow/ioc"
	"Webook/follow/repository"
	"Webook/follow/repository/cache"
	"Webook/follow/repository/dao"
	"Webook/follow/service"
	"github.com/google/wire"
)

// Injectors from wire.go:

func Init() *App {
	logger := ioc.InitLogger()
	db := ioc.InitDB(logger)
	followRelationDao := dao.NewGORMFollowRelationDAO(db)
	cmdable := ioc.InitRedisClient()
	followCache := cache.NewRedisFollowCache(cmdable)
	followRepository := repository.NewFollowRelationRepository(followRelationDao, followCache, logger)
	kafkaClient := ioc.InitKafka()
	syncProducer := ioc.InitProducer(kafkaClient)
	followProducer := events.NewProducer(syncProducer)
	followRelationService := service.NewFollowRelationService(followRepository, followProducer)
	followServiceServer := grpc2.NewFollowRelationServiceServer(followRelationService)
	client := ioc.InitEtcdClient()
	server := ioc.InitGRPCxServer(followServiceServer, client, logger)
	followConsumer := events.NewFollowEventConsumer(kafkaClient, logger, followRepository)
	consumers := ioc.NewConsumers(followConsumer)
	app := &App{
		server:    server,
		consumers: consumers,
	}
	return app
}

// wire.go:

var serviceProviderSet = wire.NewSet(dao.NewGORMFollowRelationDAO, repository.NewFollowRelationRepository, cache.NewRedisFollowCache, service.NewFollowRelationService, grpc2.NewFollowRelationServiceServer)

var thirdProvider = wire.NewSet(ioc.InitRedisClient, ioc.InitEtcdClient, ioc.InitLogger, ioc.InitDB)
