// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"Webook/follow/grpc"
	"Webook/follow/ioc"
	"Webook/follow/repository"
	"Webook/follow/repository/cache"
	"Webook/follow/repository/dao"
	"Webook/follow/service"
	"github.com/google/wire"
)

// Injectors from wire.go:

func Init() *App {
	logger := ioc.InitLogger()
	db := ioc.InitDB(logger)
	followRelationDao := dao.NewGORMFollowRelationDAO(db)
	cmdable := ioc.InitRedisClient()
	followCache := cache.NewRedisFollowCache(cmdable)
	followRepository := repository.NewFollowRelationRepository(followRelationDao, followCache, logger)
	followRelationService := service.NewFollowRelationService(followRepository)
	followServiceServer := grpc2.NewFollowRelationServiceServer(followRelationService)
	client := ioc.InitEtcdClient()
	server := ioc.InitGRPCxServer(followServiceServer, client, logger)
	app := &App{
		server: server,
	}
	return app
}

// wire.go:

var serviceProviderSet = wire.NewSet(dao.NewGORMFollowRelationDAO, repository.NewFollowRelationRepository, cache.NewRedisFollowCache, service.NewFollowRelationService, grpc2.NewFollowRelationServiceServer)

var thirdProvider = wire.NewSet(ioc.InitRedisClient, ioc.InitEtcdClient, ioc.InitLogger, ioc.InitDB)
