// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package startup

import (
	pmtv1 "Webook/api/proto/gen/api/proto/payment/v1"
	"Webook/reward/ioc"
	"Webook/reward/repository"
	"Webook/reward/repository/cache"
	"Webook/reward/repository/dao"
	"Webook/reward/service"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitWechatNativeSvc(client pmtv1.WechatPaymentServiceClient) service.RewardService {
	gormDB := InitTestDB()
	rewardDAO := dao.NewRewardGORMDAO(gormDB)
	cmdable := InitRedis()
	rewardCache := cache.NewRewardRedisCache(cmdable)
	rewardRepository := repository.NewRewardRepository(rewardDAO, rewardCache)
	loggerV1 := InitLogger()
	accountClient := ioc.InitAccountClient(ioc.InitEtcdClient())
	wechatNativeRewardService := service.NewWechatNativeRewardService(client, rewardRepository, loggerV1, accountClient)
	return wechatNativeRewardService
}

// wire.go:

var thirdPartySet = wire.NewSet(InitTestDB, InitLogger, InitRedis)
