// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"Webook/pkg/wego"
	"Webook/tag/grpc"
	"Webook/tag/ioc"
	"Webook/tag/repository"
	"Webook/tag/repository/cache"
	"Webook/tag/repository/dao"
	"Webook/tag/service"
	"github.com/google/wire"
)

// Injectors from wire.go:

func Init() *wego.App {
	logger := ioc.InitLogger()
	db := ioc.InitDB(logger)
	tagDAO := dao.NewGORMTagDAO(db)
	cmdable := ioc.InitRedis()
	tagCache := cache.NewRedisTagCache(cmdable)
	tagRepository := repository.NewTagRepository(tagDAO, tagCache, logger)
	client := ioc.InitKafka()
	producer := ioc.InitProducer(client)
	tagService := service.NewTagService(tagRepository, producer, logger)
	tagServiceServer := grpc2.NewTagServiceServer(tagService)
	clientv3Client := ioc.InitEtcdClient()
	server := ioc.InitGRPCxServer(tagServiceServer, clientv3Client, logger)
	app := &wego.App{
		GRPCServer: server,
	}
	return app
}

// wire.go:

var thirdProvider = wire.NewSet(ioc.InitRedis, ioc.InitLogger, ioc.InitDB, ioc.InitEtcdClient)
